import { shiftDate, toDateKey, toTimeKey } from "./format";
import type {
  AuditEntry,
  Customer,
  Motorcycle,
  Product,
  Purchase,
  Sale,
  ServiceJob,
  ShopNotice,
  ShopSettings,
  Staff,
  StockMovement,
  Supplier,
} from "./types";

export const STAFF: Staff[] = [
  {
    id: "U-1",
    name: "Rafael Santos",
    email: "owner@motohaus.demo",
    password: "demo1234",
    role: "Owner",
  },
  {
    id: "U-2",
    name: "Mika Reyes",
    email: "cashier@motohaus.demo",
    password: "demo1234",
    role: "Cashier",
  },
  {
    id: "U-3",
    name: "Noel Garcia",
    email: "inventory@motohaus.demo",
    password: "demo1234",
    role: "Inventory Staff",
  },
];

export const MOTORCYCLES: Motorcycle[] = [
  { make: "Honda", model: "Click 125", years: "2023-2025", label: "Honda Click 125 (2023-2025)" },
  { make: "Honda", model: "PCX 160", years: "2021-2025", label: "Honda PCX 160 (2021-2025)" },
  { make: "Honda", model: "Beat", years: "2020-2025", label: "Honda Beat (2020-2025)" },
  { make: "Yamaha", model: "NMAX 155", years: "2020-2024", label: "Yamaha NMAX 155 (2020-2024)" },
  { make: "Yamaha", model: "Aerox 155", years: "2020-2025", label: "Yamaha Aerox 155 (2020-2025)" },
  { make: "Yamaha", model: "Mio i125", years: "2019-2025", label: "Yamaha Mio i125 (2019-2025)" },
  { make: "Yamaha", model: "Sniper 150", years: "2018-2025", label: "Yamaha Sniper 150 (2018-2025)" },
  { make: "Suzuki", model: "Raider 150", years: "2019-2025", label: "Suzuki Raider 150 (2019-2025)" },
  { make: "Kawasaki", model: "Barako II", years: "2018-2024", label: "Kawasaki Barako II (2018-2024)" },
  { make: "Universal", model: "Most scooters", years: "2018-2025", label: "Universal / Most scooters" },
];

export const CATEGORIES = [
  "Brake System",
  "Chain & Sprocket",
  "Oils & Fluids",
  "Lighting",
  "Tires & Wheels",
  "Performance Parts",
  "Electrical",
  "Engine",
  "Transmission",
  "Filters",
  "Suspension",
  "Body & Controls",
] as const;

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: "MotoHaus Parts",
  tagline: "Parts that keep riders moving",
  address: "248 Quezon Ave., Quezon City",
  phone: "(02) 8555 0140",
  tin: "009-482-771-000",
  vatRate: 12,
  vatInclusive: true,
  receiptFooter: "Thank you for riding with MotoHaus. Warranty follows the part maker. Returns within 7 days with receipt.",
  lowStockAlerts: true,
};

export const SEED_PRODUCTS: Product[] = [
  {
    id: "P-1001",
    sku: "BP-HC125-01",
    name: "Ceramic Brake Pad Set",
    category: "Brake System",
    brand: "HausFriction",
    compatibility: "Honda Click 125 (2023-2025)",
    supplierId: "S-001",
    price: 680,
    cost: 390,
    stock: 3,
    min: 5,
    location: "A-02",
    description: "Front ceramic pad set for daily city riding. Quiet bite and stable heat fade for stop-and-go traffic.",
    image: "/products/brake-pads.jpg",
    warrantyDays: 90,
  },
  {
    id: "P-1002",
    sku: "CS-YNMAX-02",
    name: "428 Chain & Sprocket Kit",
    category: "Chain & Sprocket",
    brand: "GearWorks",
    compatibility: "Yamaha NMAX 155 (2020-2024)",
    supplierId: "S-002",
    price: 2450,
    cost: 1650,
    stock: 18,
    min: 6,
    location: "B-01",
    description: "Heavy-duty chain with matched front and rear sprockets. Pre-stretched for cleaner first install.",
    image: "/products/chain-sprocket.jpg",
    warrantyDays: 180,
  },
  {
    id: "P-1003",
    sku: "OF-HPCX160-03",
    name: "Synthetic Engine Oil 10W-40",
    category: "Oils & Fluids",
    brand: "ApexLube",
    compatibility: "Honda PCX 160 (2021-2025)",
    supplierId: "S-001",
    price: 520,
    cost: 330,
    stock: 24,
    min: 8,
    location: "C-04",
    description: "1L synthetic scooter oil for regular 1,000–2,000 km service intervals.",
    image: "/products/engine-oil.jpg",
    warrantyDays: 0,
  },
  {
    id: "P-1004",
    sku: "LL-YAEROX-04",
    name: "LED Headlight Bulb",
    category: "Lighting",
    brand: "VoltEdge",
    compatibility: "Yamaha Aerox 155 (2020-2025)",
    supplierId: "S-003",
    price: 890,
    cost: 540,
    stock: 7,
    min: 4,
    location: "D-03",
    description: "Bright plug-and-play LED replacement with cooling fins. Street-legal white beam.",
    image: "/products/led-bulb.jpg",
    warrantyDays: 365,
  },
  {
    id: "P-1005",
    sku: "TI-SRAIDER-05",
    name: "Tubeless Tire 90/80-17",
    category: "Tires & Wheels",
    brand: "GripLine",
    compatibility: "Suzuki Raider 150 (2019-2025)",
    supplierId: "S-002",
    price: 3150,
    cost: 2280,
    stock: 0,
    min: 3,
    location: "E-01",
    description: "Street tire with wet-weather siping. Balanced for daily commuting and weekend runs.",
    image: "/products/tire.jpg",
    warrantyDays: 120,
  },
  {
    id: "P-1006",
    sku: "SP-KBARAKO-06",
    name: "Heavy-Duty Clutch Spring Set",
    category: "Performance Parts",
    brand: "BarakoTech",
    compatibility: "Kawasaki Barako II (2018-2024)",
    supplierId: "S-002",
    price: 760,
    cost: 470,
    stock: 11,
    min: 4,
    location: "B-06",
    description: "Replacement clutch springs for utility bikes that haul cargo through city heat.",
    image: "/products/clutch-springs.jpg",
    warrantyDays: 90,
  },
  {
    id: "P-1007",
    sku: "EN-HBEAT-07",
    name: "Iridium Spark Plug",
    category: "Engine",
    brand: "FirePoint",
    compatibility: "Honda Beat (2020-2025)",
    supplierId: "S-001",
    price: 280,
    cost: 145,
    stock: 32,
    min: 10,
    location: "C-01",
    description: "Fine-wire iridium plug for easier cold starts and a cleaner idle.",
    image: "/products/spark-plug.jpg",
    warrantyDays: 180,
  },
  {
    id: "P-1008",
    sku: "TR-YMIO-08",
    name: "CVT Drive Belt",
    category: "Transmission",
    brand: "BeltCore",
    compatibility: "Yamaha Mio i125 (2019-2025)",
    supplierId: "S-002",
    price: 980,
    cost: 610,
    stock: 9,
    min: 5,
    location: "B-03",
    description: "OEM-spec toothed belt. Replace with rollers during a CVT clean for best life.",
    image: "/products/cvt-belt.jpg",
    warrantyDays: 120,
  },
  {
    id: "P-1009",
    sku: "FL-HC125-09",
    name: "Air Filter Element",
    category: "Filters",
    brand: "HausFilter",
    compatibility: "Honda Click 125 (2023-2025)",
    supplierId: "S-001",
    price: 320,
    cost: 170,
    stock: 16,
    min: 6,
    location: "C-02",
    description: "Drop-in paper element. Swap every 4,000 km in dusty city routes.",
    image: "/products/air-filter.jpg",
    warrantyDays: 30,
  },
  {
    id: "P-1010",
    sku: "EL-UNIV-10",
    name: "Lithium Motorcycle Battery 12V",
    category: "Electrical",
    brand: "VoltEdge",
    compatibility: "Universal / Most scooters",
    supplierId: "S-003",
    price: 2890,
    cost: 1980,
    stock: 5,
    min: 3,
    location: "D-01",
    description: "Compact 12V lithium pack with standard terminals. Lighter than flooded batteries.",
    image: "/products/battery.jpg",
    warrantyDays: 365,
  },
  {
    id: "P-1011",
    sku: "OF-DOT4-11",
    name: "Brake Fluid DOT 4",
    category: "Oils & Fluids",
    brand: "ApexLube",
    compatibility: "Universal / Most scooters",
    supplierId: "S-001",
    price: 240,
    cost: 125,
    stock: 21,
    min: 8,
    location: "C-05",
    description: "500ml DOT 4 fluid for disc brake systems. Flush every two years.",
    image: "/products/engine-oil.jpg",
    warrantyDays: 0,
  },
  {
    id: "P-1012",
    sku: "BP-YSNIP-12",
    name: "Disc Brake Rotor 220mm",
    category: "Brake System",
    brand: "HausFriction",
    compatibility: "Yamaha Sniper 150 (2018-2025)",
    supplierId: "S-002",
    price: 1680,
    cost: 1090,
    stock: 4,
    min: 3,
    location: "A-04",
    description: "Stainless ventilated rotor. True-running face for clean pad seating.",
    image: "/products/brake-pads.jpg",
    warrantyDays: 180,
  },
  {
    id: "P-1013",
    sku: "SU-HC125-13",
    name: "Rear Shock Absorber",
    category: "Suspension",
    brand: "RideLink",
    compatibility: "Honda Click 125 (2023-2025)",
    supplierId: "S-002",
    price: 1850,
    cost: 1180,
    stock: 6,
    min: 3,
    location: "E-03",
    description: "Gas-charged rear shock for two-up commuting. Direct bolt-on.",
    image: "/products/clutch-springs.jpg",
    warrantyDays: 180,
  },
  {
    id: "P-1014",
    sku: "BD-UNIV-14",
    name: "Handle Grip Set",
    category: "Body & Controls",
    brand: "RideLink",
    compatibility: "Universal / Most scooters",
    supplierId: "S-003",
    price: 220,
    cost: 95,
    stock: 28,
    min: 10,
    location: "D-06",
    description: "Soft-touch dual-density grips. Fits standard 22mm bars.",
    image: "/products/cvt-belt.jpg",
    warrantyDays: 30,
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "C-001",
    name: "Marco Villanueva",
    phone: "0917 555 0142",
    email: "marco.demo@example.com",
    motorcycle: "Honda Click 125 (2023-2025)",
    notes: "Prefers GCash. Regular oil change every 1,500 km.",
    purchases: 4280,
    points: 42,
    last: toDateKey(shiftDate(-1)),
  },
  {
    id: "C-002",
    name: "Janelle Cruz",
    phone: "0920 555 0198",
    email: "janelle.demo@example.com",
    motorcycle: "Yamaha NMAX 155 (2020-2024)",
    notes: "Asked for chain kit quote last week.",
    purchases: 7950,
    points: 79,
    last: toDateKey(shiftDate(0, 11, 20)),
  },
  {
    id: "C-003",
    name: "Paolo Mendoza",
    phone: "0918 555 0126",
    email: "paolo.demo@example.com",
    motorcycle: "Suzuki Raider 150 (2019-2025)",
    notes: "Waiting on tire restock.",
    purchases: 3150,
    points: 31,
    last: toDateKey(shiftDate(-5)),
  },
  {
    id: "C-004",
    name: "Aira Dela Peña",
    phone: "0916 555 0104",
    email: "aira.demo@example.com",
    motorcycle: "Honda PCX 160 (2021-2025)",
    notes: "",
    purchases: 1560,
    points: 15,
    last: toDateKey(shiftDate(-2)),
  },
  {
    id: "C-005",
    name: "Gino Ramirez",
    phone: "0927 555 0188",
    email: "gino.demo@example.com",
    motorcycle: "Yamaha Aerox 155 (2020-2025)",
    notes: "Night shift rider. Comes in after 8pm.",
    purchases: 890,
    points: 8,
    last: toDateKey(shiftDate(-3)),
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: "S-001",
    company: "RiderPro Supply",
    contact: "Aileen Tan",
    phone: "(02) 8555 0140",
    email: "orders@riderpro.demo",
    status: "Active",
    notes: "2-day Metro Manila lead. Best for oils and filters.",
  },
  {
    id: "S-002",
    company: "GearWorks PH",
    contact: "Luis Navarro",
    phone: "(02) 8555 0191",
    email: "sales@gearworks.demo",
    status: "Active",
    notes: "Chains, tires, performance. Weekly truck on Thursdays.",
  },
  {
    id: "S-003",
    company: "VoltEdge Motors",
    contact: "Nica Ramos",
    phone: "(02) 8555 0177",
    email: "hello@voltedge.demo",
    status: "Active",
    notes: "Lighting and electrical. Same-day QC for in-stock SKUs.",
  },
];

function sale(
  id: string,
  days: number,
  hours: number,
  minutes: number,
  customer: Customer | null,
  productIds: { id: string; qty: number }[],
  payment: Sale["payment"],
  staff: Staff,
  status: Sale["status"] = "Completed",
): Sale {
  const when = shiftDate(days, hours, minutes);
  const items = productIds.map((row) => {
    const p = SEED_PRODUCTS.find((x) => x.id === row.id)!;
    return {
      productId: p.id,
      name: p.name,
      sku: p.sku,
      qty: row.qty,
      price: p.price,
      cost: p.cost,
    };
  });
  const subtotal = items.reduce((s, i) => s + i.qty * i.price, 0);
  return {
    id,
    customerId: customer?.id ?? null,
    customer: customer?.name ?? "Walk-in customer",
    items,
    subtotal,
    discount: 0,
    tax: 0,
    total: subtotal,
    payment,
    received: subtotal,
    change: 0,
    staff: staff.name,
    staffId: staff.id,
    date: toDateKey(when),
    time: toTimeKey(when),
    status,
    note: "",
  };
}

const owner = STAFF[0]!;
const cashier = STAFF[1]!;

export const SEED_SALES: Sale[] = [
  sale("TXN-TODAY-018", 0, 9, 12, SEED_CUSTOMERS[1]!, [{ id: "P-1003", qty: 2 }], "Cash", cashier, "Ready"),
  sale("TXN-TODAY-017", 0, 10, 41, SEED_CUSTOMERS[0]!, [{ id: "P-1001", qty: 1 }], "GCash", cashier),
  sale("TXN-TODAY-016", 0, 13, 5, null, [{ id: "P-1004", qty: 1 }], "Card", owner),
  sale("TXN-YD-015", -1, 16, 22, SEED_CUSTOMERS[3]!, [{ id: "P-1003", qty: 1 }, { id: "P-1007", qty: 1 }], "GCash", cashier),
  sale("TXN-YD-014", -1, 11, 8, SEED_CUSTOMERS[4]!, [{ id: "P-1004", qty: 1 }], "Cash", cashier),
  sale("TXN-2D-013", -2, 15, 40, SEED_CUSTOMERS[1]!, [{ id: "P-1002", qty: 1 }], "Bank Transfer", owner),
  sale("TXN-3D-012", -3, 14, 18, null, [{ id: "P-1014", qty: 2 }, { id: "P-1007", qty: 1 }], "Cash", cashier),
  sale("TXN-4D-011", -4, 12, 2, SEED_CUSTOMERS[0]!, [{ id: "P-1009", qty: 1 }, { id: "P-1003", qty: 1 }], "GCash", cashier),
  sale("TXN-5D-010", -5, 17, 33, SEED_CUSTOMERS[2]!, [{ id: "P-1006", qty: 1 }], "Card", owner),
  sale("TXN-6D-009", -6, 10, 55, null, [{ id: "P-1008", qty: 1 }], "Cash", cashier),
  sale("TXN-8D-008", -8, 13, 14, SEED_CUSTOMERS[3]!, [{ id: "P-1010", qty: 1 }], "GCash", owner),
  sale("TXN-10D-007", -10, 16, 47, SEED_CUSTOMERS[1]!, [{ id: "P-1003", qty: 3 }], "Cash", cashier),
];

export const SEED_PURCHASES: Purchase[] = [
  {
    id: "PO-OPEN-004",
    supplierId: "S-002",
    supplier: "GearWorks PH",
    items: [
      { productId: "P-1005", name: "Tubeless Tire 90/80-17", qty: 6, cost: 2280 },
      { productId: "P-1002", name: "428 Chain & Sprocket Kit", qty: 8, cost: 1650 },
    ],
    total: 6 * 2280 + 8 * 1650,
    status: "Ordered",
    date: toDateKey(shiftDate(-2)),
    note: "Rush the tires — Raider 150 is sold out.",
  },
  {
    id: "PO-DONE-003",
    supplierId: "S-001",
    supplier: "RiderPro Supply",
    items: [
      { productId: "P-1003", name: "Synthetic Engine Oil 10W-40", qty: 24, cost: 330 },
      { productId: "P-1001", name: "Ceramic Brake Pad Set", qty: 10, cost: 390 },
    ],
    total: 24 * 330 + 10 * 390,
    status: "Received",
    date: toDateKey(shiftDate(-6)),
    note: "",
  },
];

export const SEED_SERVICES: ServiceJob[] = [
  {
    id: "WO-TODAY-03",
    customerId: "C-001",
    customer: "Marco Villanueva",
    motorcycle: "Honda Click 125 (2023-2025)",
    complaint: "Squeal on front brake + scheduled oil change",
    labor: 350,
    parts: [
      {
        productId: "P-1001",
        name: "Ceramic Brake Pad Set",
        sku: "BP-HC125-01",
        qty: 1,
        price: 680,
        cost: 390,
      },
    ],
    status: "In progress",
    staff: "Rafael Santos",
    date: toDateKey(),
    due: toDateKey(),
  },
  {
    id: "WO-TODAY-02",
    customerId: "C-002",
    customer: "Janelle Cruz",
    motorcycle: "Yamaha NMAX 155 (2020-2024)",
    complaint: "CVT chatter at 40 kph",
    labor: 650,
    parts: [
      {
        productId: "P-1008",
        name: "CVT Drive Belt",
        sku: "TR-YMIO-08",
        qty: 1,
        price: 980,
        cost: 610,
      },
    ],
    status: "Queued",
    staff: "Mika Reyes",
    date: toDateKey(),
    due: toDateKey(shiftDate(1)),
  },
  {
    id: "WO-YD-01",
    customerId: "C-004",
    customer: "Aira Dela Peña",
    motorcycle: "Honda PCX 160 (2021-2025)",
    complaint: "1,000 km service",
    labor: 250,
    parts: [
      {
        productId: "P-1003",
        name: "Synthetic Engine Oil 10W-40",
        sku: "OF-HPCX160-03",
        qty: 1,
        price: 520,
        cost: 330,
      },
    ],
    status: "Completed",
    staff: "Rafael Santos",
    date: toDateKey(shiftDate(-1)),
    due: toDateKey(shiftDate(-1)),
  },
];

export const SEED_MOVEMENTS: StockMovement[] = [
  {
    id: "MV-1",
    productId: "P-1001",
    product: "Ceramic Brake Pad Set",
    delta: -1,
    reason: "sale",
    ref: "TXN-TODAY-017",
    user: "Mika Reyes",
    date: toDateKey(),
    time: "10:41",
  },
  {
    id: "MV-2",
    productId: "P-1003",
    product: "Synthetic Engine Oil 10W-40",
    delta: 24,
    reason: "purchase",
    ref: "PO-DONE-003",
    user: "Rafael Santos",
    date: toDateKey(shiftDate(-6)),
    time: "10:05",
  },
];

export const SEED_AUDIT: AuditEntry[] = [
  {
    id: "AU-1",
    action: "Sale completed",
    detail: "TXN-TODAY-017 · Ceramic Brake Pad Set",
    user: "Mika Reyes",
    date: toDateKey(),
    time: "10:41",
  },
  {
    id: "AU-2",
    action: "Stock adjusted",
    detail: "Ceramic Brake Pad Set marked low",
    user: "Noel Garcia",
    date: toDateKey(),
    time: "09:18",
  },
  {
    id: "AU-3",
    action: "Purchase received",
    detail: "PO-DONE-003",
    user: "Rafael Santos",
    date: toDateKey(shiftDate(-6)),
    time: "10:05",
  },
];

export const SEED_NOTICES: ShopNotice[] = [
  {
    id: "N-1",
    text: "Ceramic Brake Pad Set is below minimum (3 / 5)",
    unread: true,
    kind: "stock",
    date: toDateKey(),
  },
  {
    id: "N-2",
    text: "Tubeless Tire 90/80-17 is out of stock",
    unread: true,
    kind: "stock",
    date: toDateKey(),
  },
  {
    id: "N-3",
    text: "Purchase PO-OPEN-004 from GearWorks PH is still open",
    unread: false,
    kind: "purchase",
    date: toDateKey(shiftDate(-2)),
  },
];

export function cloneSeed() {
  return {
    products: structuredClone(SEED_PRODUCTS),
    customers: structuredClone(SEED_CUSTOMERS),
    suppliers: structuredClone(SEED_SUPPLIERS),
    sales: structuredClone(SEED_SALES),
    purchases: structuredClone(SEED_PURCHASES),
    services: structuredClone(SEED_SERVICES),
    movements: structuredClone(SEED_MOVEMENTS),
    audit: structuredClone(SEED_AUDIT),
    notices: structuredClone(SEED_NOTICES),
    returns: [] as import("./types").ReturnTicket[],
    settings: structuredClone(DEFAULT_SETTINGS),
    shifts: [] as import("./types").Shift[],
  };
}
